language: rust
rust:
 - stable
 - beta
 - nightly
matrix:
  allow_failures:
    - rust: nightly
# Enforce that all new commits are signed off according to the DCO,
# per CONTRIBUTING.md. Prior commits are either pre-fork, are signed off,
# or were made by Mark Thebridge, who hereby certifies the DCO with regard
# to each such commit.
#
# We then build all the code, then test it.
before_script:
  - rustup component add clippy
script:
- |
  DCO_SIGNING_BASE_COMMIT=b00f12dc7afa4400af1289a7f69e570148ae16e5 &&
  if git log ${DCO_SIGNING_BASE_COMMIT}.. --grep "^signed-off-by: .\+@.\+" --regexp-ignore-case --invert-grep --no-merges | grep ^ ;
  then echo '**One or more commits are not signed off!' ; /bin/false ; fi
- cargo clippy --all-targets --all-features --all -- -D warnings
- cargo clippy --all-targets --no-default-features --all -- -D warnings
- cargo test --all --all-features
- cargo test --all --no-default-features
