[package]
authors = ["Metaswitch Networks Ltd"]
name = "slog-extlog"
version = "3.1.0"

[[bench]]
harness = false
name = "stats"

[dependencies]
erased-serde = "0.3"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1"
tokio-core = "0.1"
tokio-timer = "0.1"

[dependencies.iobuffer]
git = "ssh://github.com/Metaswitch/iobuffer.git"

[dependencies.slog]
features = ["nested-values"]
version = "=2.1.1"

[dependencies.slog-json]
features = ["nested-values"]
version = "2.1"

[dev-dependencies]
bencher = "0.1.5"

[dev-dependencies.slog-extlog-derive]
path = "slog-extlog-derive"

[workspace]
members = ["slog-extlog-derive"]
