[package]
authors = ["Metaswitch Networks Ltd"]
name = "slog-extlog"
version = "3.1.0"
license = "Apache-2.0"
description = "Object-based logging and statistics tracking through logs"
homepage = "https://github.com/Metaswitch/slog-extlog"
repository = "https://github.com/Metaswitch/slog-extlog"
keywords = ["slog", "log", "logging"]
readme = "README.md"

[[bench]]
harness = false
name = "stats"

[dependencies]
erased-serde = "0.3"
futures = "0.1"
iobuffer= "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1"
tokio-core = "0.1"
tokio-timer = "0.1"

[dependencies.slog]
features = ["nested-values"]
version = "=2.1.1"

[dependencies.slog-json]
features = ["nested-values"]
version = "2.1"

[dev-dependencies]
bencher = "0.1.5"

[dev-dependencies.slog-extlog-derive]
path = "slog-extlog-derive"

[workspace]
members = ["slog-extlog-derive"]
